<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/normalize.css" />
		<link rel="stylesheet" href="../css/stylesheet.css" />
		<title>Arena</title>
	</head>
	<body>
		<header>
			<h1>Arena</h1>
		</header>
		<main>
			<section id="buttonEntrez">
				<a href="createPerso.php">Entrez</a>
			</section>
		</main>
		<?php 
include 'footer.phtml'; 
?>